### PR TITLE
Merge request & Fix request

### PR DESCRIPTION
**Pull request by ghost**
I run "extract-files.sh" file, but No such or file error.
Commit : [Link](https://github.com/cloud9350/android_device_lge_fx1sk/commit/744e0780f3c4f9a5f236fe88c7a9e47cc0761b29)

If you have the time, please fix
I must Fix the kernel. :smile:

### CODE REVIEW

**Comment by chevanlol360** [comment]
Hey Cloud9350,

I forked this kernel from dizsell2008 on bit bucket here 

https://bitbucket.org/diszell2008/android_device_lge_vu2u/src

https://bitbucket.org/diszell2008/android_kernel_lge_vu2u/src

Its his kernel but it doesn't build for me :( so i get an error too.

I messaged him on bitbucket asking if he could help but he didn't respond.

I also tried building with the device tree that he has but those don't build either,  it errors out and the terminal said that it is "treating all warnings as errors" and I didn't know how to fix it.

Thanks for the merger

**Comment by ghost** [comment]
@chevanlol360 The cause of the error, because it is this kernel source branch a jellybean.
And all of this causes Device Tree. (Wrong init.d, not link, etc...)

Workaround : porting the kernel OR edit init.d files

**Comment by ghost** [comment]
@chevanlol360 And since the last commit 2014, most likely no longer inactive.

**Comment by chevanlol360** [comment]
@cloud9350

I tried building the kernel alone without building cyanogenmod and the kernel still didn't build since the kernel was already broken when disell2008 uploaded it to bitbucket.

Its kind of hard to port something that is broken to begin with. Although the error that you get in terminal doesn't seem that hard to fix, I still have no idea where to begin. I've been out of the whole building environment for some time now, been too busy to work on building stuff.

You try building the kernel alone without cyanogenmod and you will see the small error I'm talking about. 

And yeah I think he stopped working on it. 
Tekcafe has a bit bucket but all of their repos are private so we can't see them, I think tekcafe has the working vu2 cm12.0/12.1 kernel source.

**Comment by ghost** [comment]
@chevanlol360 Android is a GPL license, which is why private care :)

I would try porting Android 5.1 Kernel tomorrow. (Now KST PM 11:09)
And TeamWin Recovery ...

**Comment by chevanlol360** [comment]
If you need help with TWRP Recovery let me know since i can help. but we would need to use stock kernel for the fx1sk. I Ported CWM and Philz recovery to the USA LTE over a year ago. 

http://androidforums.com/threads/root-recovery-touch-non-touch-optimus-f7-fx1.829374/

Here is the tree i made for building cwm and philz recovery,

https://github.com/chevanlol360/android_device_lge_fx1_cm

**Comment by ghost** [comment]
@chevanlol360 Thanks.
Forked

**Pull request closed without merging**
